### ISSUE TITLE
As a player I want to be able to choose between multiple game modes such as jokes,  languages, movie quotes, and last-words, in order to have a similar game experience as with the  definition, but experience variety at the same time.

### ISSUE THREAD

**Issue by Elyisha** [sopra-fs24-group-38/sopra-fs24-group-38-server#103]
**Development Tasks**
- [x] sopra-fs24-group-38/sopra-fs24-group-38-client#55
- [x] sopra-fs24-group-38/sopra-fs24-group-38-server#105
- [x] sopra-fs24-group-38/sopra-fs24-group-38-client#54
- [x] sopra-fs24-group-38/sopra-fs24-group-38-client#53
- [x] sopra-fs24-group-38/sopra-fs24-group-38-server#108

**Acceptance criteria**
- [x] The game master can switch between several modes in the lobby
- [x] Inside the rules view, every additional gamemode should be explained.
