### ISSUE TITLE
As a user I want a resilient application that ensures uninterrupted play, even when the  primary API faces temporary unavailability in order to provide the same game experience even  with the API being temporary not available.

### ISSUE THREAD

**Issue by Elyisha** [sopra-fs24-group-38/sopra-fs24-group-38-server#109]
**Development Tasks**
- [x] sopra-fs24-group-38/sopra-fs24-group-38-server#110
- [x] sopra-fs24-group-38/sopra-fs24-group-38-server#111
- [x] sopra-fs24-group-38/sopra-fs24-group-38-server#112
- [x] sopra-fs24-group-38/sopra-fs24-group-38-client#56

**Acceptance criteria**
- [x] The game provides a mechanism to check the API's availability and content quality, ensuring it meets acceptable standards for a smooth gaming experience
- [x] The game uses a fallback data set in case the API is not available or malfunctions
