### ISSUE TITLE
As a game host I want to be able to customize the game by choosing corresponding  settings, in order to have an additional possibility of customization.

### ISSUE THREAD

**Issue by Elyisha** [sopra-fs24-group-38/sopra-fs24-group-38-server#114]
**Development Tasks**
- [ ] sopra-fs24-group-38/sopra-fs24-group-38-client#58
- [x] sopra-fs24-group-38/sopra-fs24-group-38-client#59
- [ ] sopra-fs24-group-38/sopra-fs24-group-38-client#57
- [ ] sopra-fs24-group-38/sopra-fs24-group-38-server#118
- [ ] sopra-fs24-group-38/sopra-fs24-group-38-server#119
- [ ] sopra-fs24-group-38/sopra-fs24-group-38-server#120

**Acceptance criteria**
- [ ] The length of a game can be chosen by the game master
- [ ] It is possible to set a number of points as the finishing criteria
- [ ] It is possible to set an amount of players that can participate in the game
