### ISSUE TITLE
As a player I want to be able to see my past game stats, in order to to review and track my  progress over time.

### ISSUE THREAD

**Issue by Elyisha** [sopra-fs24-group-38/sopra-fs24-group-38-server#121]
**Development Tasks**
- [x] sopra-fs24-group-38/sopra-fs24-group-38-client#60
- [x] sopra-fs24-group-38/sopra-fs24-group-38-server#123
- [x] sopra-fs24-group-38/sopra-fs24-group-38-server#124

**Acceptance criteria**
- [x] The player can see his past game stats by clicking on a button in the start screen
- [x] Everytime a game ends, the current stats (points achieved, players fooled etc.) are added to the overall stats
