### ISSUE TITLE
As a game host I want to be able to fill the missing player slots with AI players, in order to  have the same user experience even if not that many players are available.

### ISSUE THREAD

**Issue by Elyisha** [sopra-fs24-group-38/sopra-fs24-group-38-server#125]
**Development Tasks**
- [x] sopra-fs24-group-38/sopra-fs24-group-38-client#62
- [x] sopra-fs24-group-38/sopra-fs24-group-38-client#63
- [x] sopra-fs24-group-38/sopra-fs24-group-38-client#61
- [x] sopra-fs24-group-38/sopra-fs24-group-38-server#129
- [x] sopra-fs24-group-38/sopra-fs24-group-38-server#130
- [x] sopra-fs24-group-38/sopra-fs24-group-38-server#131

**Acceptance criteria**
- [x] In the lobby view the game master can choose to add AI players to the game which imitate real players
- [x] The AI players each have a name and an avatar
