### ISSUE TITLE
As a user, I want to see myself as an avatar in order to be able to distinguish better between  myself and other players.

### ISSUE THREAD

**Issue by Elyisha** [sopra-fs24-group-38/sopra-fs24-group-38-server#132]
**Development Tasks**
- [ ] sopra-fs24-group-38/sopra-fs24-group-38-client#65
- [x] sopra-fs24-group-38/sopra-fs24-group-38-client#64
- [ ] sopra-fs24-group-38/sopra-fs24-group-38-server#135
- [ ] sopra-fs24-group-38/sopra-fs24-group-38-server#136

**Acceptance criteria**
- [ ] The game lets players chose their own avatar
