### ISSUE TITLE
 As a user, I want the game to verify my responses in order to maintain a challenging and  interesting environment

### ISSUE THREAD

**Issue by Elyisha** [sopra-fs24-group-38/sopra-fs24-group-38-server#137]
**Development Tasks**
- [x] sopra-fs24-group-38/sopra-fs24-group-38-client#67
- [x] sopra-fs24-group-38/sopra-fs24-group-38-client#66
- [x] sopra-fs24-group-38/sopra-fs24-group-38-server#140
- [x] sopra-fs24-group-38/sopra-fs24-group-38-server#141

**Acceptance criteria**
- [x] The game is able to recognize when the user has entered the correct reply to the current challange
