### ISSUE TITLE
As a Gamemaster I want to be able to set different modes in the Lobby 

### ISSUE THREAD

**Issue by samuelfrnk** [sopra-fs24-group-38/sopra-fs24-group-38-server#209]
DEV TASKS: 

- [x] sopra-fs24-group-38/sopra-fs24-group-38-server#207
- [x] sopra-fs24-group-38/sopra-fs24-group-38-server#208
- [x] sopra-fs24-group-38/sopra-fs24-group-38-client#88
- [x] sopra-fs24-group-38/sopra-fs24-group-38-client#89

**Acceptance criteria**
- [x] It is possible to choose several modes at the same time and corresponding challenges are then played. 
- [x] During the game it is displayed from which category this challenge belongs to. 
- [x] A current round / from rounds information is displayed during the game rounds.
