### ISSUE TITLE
As a player I want to be able to use nobody is perfect in a reliable way. 

### ISSUE THREAD

**Issue by samuelfrnk** [sopra-fs24-group-38/sopra-fs24-group-38-server#212]
DEV TASKS: 

- [x] sopra-fs24-group-38/sopra-fs24-group-38-server#210
- [x] sopra-fs24-group-38/sopra-fs24-group-38-server#211
- [x] sopra-fs24-group-38/sopra-fs24-group-38-server#219
- [x] sopra-fs24-group-38/sopra-fs24-group-38-server#217
- [x] sopra-fs24-group-38/sopra-fs24-group-38-server#222
- [x] sopra-fs24-group-38/sopra-fs24-group-38-server#231
- [x] sopra-fs24-group-38/sopra-fs24-group-38-server#233

- [x] sopra-fs24-group-38/sopra-fs24-group-38-client#90
- [x] sopra-fs24-group-38/sopra-fs24-group-38-client#91
- [x] sopra-fs24-group-38/sopra-fs24-group-38-client#96
- [x] sopra-fs24-group-38/sopra-fs24-group-38-client#97
- [x] sopra-fs24-group-38/sopra-fs24-group-38-client#98
 - [x] sopra-fs24-group-38/sopra-fs24-group-38-client#87

**Acceptance criteria**
- [ ] It is possible to recover (at least quit and logout from each state) 
- [ ] Each challenge does not appear twice if a few rounds are played at the same time.
- [ ] It is possible to leave the game in any state.
