### ISSUE TITLE
As a player of nobody is perfect i want to be using an application which provides a pleasant gameflow through reliable reuqests to the chatGPT API

### ISSUE THREAD

**Issue by samuelfrnk** [sopra-fs24-group-38/sopra-fs24-group-38-server#235]
**Development Tasks**
- [x] sopra-fs24-group-38/sopra-fs24-group-38-server#236
- [x] sopra-fs24-group-38/sopra-fs24-group-38-server#237
- [x] sopra-fs24-group-38/sopra-fs24-group-38-server#238
- [x] sopra-fs24-group-38/sopra-fs24-group-38-server#239
- [x] sopra-fs24-group-38/sopra-fs24-group-38-server#248
- [x] sopra-fs24-group-38/sopra-fs24-group-38-server#254
- [x] #256
- [x] #257
- [x] #258 

**Acceptance criteria**
- [x] The challenge modes appear shuffeld in game. 
- [x] The desired challenges are being fetched evenly. 
- [x] It is not possible to identify the AI players definition just looking at lower case characters.
- [x] Game preparing doesnt go longer than 40 seconds on average
