### ISSUE TITLE
As a player who opens the game, I want to be able to register as a user with a username  and password in order to participate in the game.

### ISSUE THREAD

**Issue by Elyisha** [sopra-fs24-group-38/sopra-fs24-group-38-server#27]
**Development tasks** 
- [x] sopra-fs24-group-38/sopra-fs24-group-38-server#28
- [x] sopra-fs24-group-38/sopra-fs24-group-38-client#16
- [x] sopra-fs24-group-38/sopra-fs24-group-38-client#18
- [x] sopra-fs24-group-38/sopra-fs24-group-38-server#31
- [x] sopra-fs24-group-38/sopra-fs24-group-38-client#17
- [x] sopra-fs24-group-38/sopra-fs24-group-38-client#15

**Acceptance criteria** 
- [x] It is possible to register as a user with a unique username and a password.
- [x]  During the registration it is possible to toggle between showing and hiding the password.
- [x] The user is capable of automatic re-login after a sudden disconnection.
