### ISSUE TITLE
As a registered player who opens the game, I want to be able to login as a user with a username and password in order to participate in the game.

### ISSUE THREAD

**Issue by Elyisha** [sopra-fs24-group-38/sopra-fs24-group-38-server#34]
**Development Tasks**
- [x] sopra-fs24-group-38/sopra-fs24-group-38-client#20
- [x] sopra-fs24-group-38/sopra-fs24-group-38-client#19
- [x] sopra-fs24-group-38/sopra-fs24-group-38-server#37
- [x] sopra-fs24-group-38/sopra-fs24-group-38-server#38

**Acceptance criteria**
- [x] In the landing page it can be decided to switch between a login and a register form.
- [x] After a successful login, a page which allows you to create and join lobbies is shown.
- [x] A User has the possibility to display the characters which he typed in as a password and also hide them again.
