### ISSUE TITLE
As a logged in player I want to be able to create a lobby in order to play with friends.

### ISSUE THREAD

**Issue by Elyisha** [sopra-fs24-group-38/sopra-fs24-group-38-server#39]
**Development Tasks**
- [x] sopra-fs24-group-38/sopra-fs24-group-38-server#40
- [x] sopra-fs24-group-38/sopra-fs24-group-38-client#23
- [x] sopra-fs24-group-38/sopra-fs24-group-38-client#24
- [x] sopra-fs24-group-38/sopra-fs24-group-38-client#21
- [x] sopra-fs24-group-38/sopra-fs24-group-38-server#44
- [x] sopra-fs24-group-38/sopra-fs24-group-38-server#45
- [x] sopra-fs24-group-38/sopra-fs24-group-38-server#46
- [x] sopra-fs24-group-38/sopra-fs24-group-38-server#47
- [x] sopra-fs24-group-38/sopra-fs24-group-38-server#172

**Acceptance criteria**
- [x] The user sees a view with the possibility to create a new lobby.
- [x] The user can see a generated game pin upon creating a lobby.
- [x] The user sees a game master view, where they can see the other joining
 players.
- [x] There can be multiple lobbies at the same time
