### ISSUE TITLE
As a logged in player I want to be able to join a lobby in order to play with friends.

### ISSUE THREAD

**Issue by Elyisha** [sopra-fs24-group-38/sopra-fs24-group-38-server#49]
**Development tasks**
- [x] sopra-fs24-group-38/sopra-fs24-group-38-client#26
- [x] sopra-fs24-group-38/sopra-fs24-group-38-client#27
- [x] sopra-fs24-group-38/sopra-fs24-group-38-server#52
- [x] sopra-fs24-group-38/sopra-fs24-group-38-server#53
- [x] sopra-fs24-group-38/sopra-fs24-group-38-server#54
- [x] sopra-fs24-group-38/sopra-fs24-group-38-client#25

**Acceptance criteria**
- [x] The user sees a view presenting the option to join a new lobby by entering a specific
 gamepin.
- [x] The user sees a "wait for others" view upon joining a lobby
