### ISSUE TITLE
As a lobby creator player I want to be able to customize and start a new game within a  lobby in order to play with friends.

### ISSUE THREAD

**Issue by Elyisha** [sopra-fs24-group-38/sopra-fs24-group-38-server#59]
**Development task**
- [x] sopra-fs24-group-38/sopra-fs24-group-38-client#29
- [x] sopra-fs24-group-38/sopra-fs24-group-38-server#61
- [x] sopra-fs24-group-38/sopra-fs24-group-38-server#62
- [x] sopra-fs24-group-38/sopra-fs24-group-38-client#31
- [x] sopra-fs24-group-38/sopra-fs24-group-38-client#30
- [x] sopra-fs24-group-38/sopra-fs24-group-38-server#65
- [x] sopra-fs24-group-38/sopra-fs24-group-38-server#177

**Acceptance criteria**
- [x] The game master can start the game
- [x] The game mode can be chosen by the game master
