### ISSUE TITLE
As a player in-game I want to be able to see the current round’s challenge and enter my  reply in order to participate in the game.

### ISSUE THREAD

**Issue by Elyisha** [sopra-fs24-group-38/sopra-fs24-group-38-server#66]
**Development Tasks**
- [x] sopra-fs24-group-38/sopra-fs24-group-38-client#35
- [x] sopra-fs24-group-38/sopra-fs24-group-38-client#34
- [x] sopra-fs24-group-38/sopra-fs24-group-38-server#69
- [x] sopra-fs24-group-38/sopra-fs24-group-38-server#70
- [x] sopra-fs24-group-38/sopra-fs24-group-38-server#71
- [x] sopra-fs24-group-38/sopra-fs24-group-38-server#72
- [x] sopra-fs24-group-38/sopra-fs24-group-38-client#32

**Acceptance criteria**
- [x] The answers are being persisted during the round.
- [x] The game keeps track of how many answers arrived and performs a redirect once it is time to vote.
