### ISSUE TITLE
As a player in-game I want to be able to choose an option which I think is the most correct  and to post my vote in order to participate in the game.

### ISSUE THREAD

**Issue by Elyisha** [sopra-fs24-group-38/sopra-fs24-group-38-server#75]
**Development Task**
- [x] sopra-fs24-group-38/sopra-fs24-group-38-client#36
- [x] sopra-fs24-group-38/sopra-fs24-group-38-client#52
- [x] sopra-fs24-group-38/sopra-fs24-group-38-client#51
- [x] sopra-fs24-group-38/sopra-fs24-group-38-client#49
- [x] sopra-fs24-group-38/sopra-fs24-group-38-server#80
- [x] sopra-fs24-group-38/sopra-fs24-group-38-server#81
- [x] sopra-fs24-group-38/sopra-fs24-group-38-server#82

**Acceptance criteria**
- [x] The player can see all the replies and the correct one randomly shuffled.
- [x] The player can select a reply and has the possibility to confirm that choice.
- [x] The player sees how the other players voted after every vote was cast.
- [x] The game evaluates the votes and decides which player receives how many points.
- [x] Once all votes are cast, the game initiates a redirect to the next round.
