### ISSUE TITLE
As an in-game player I want to be able to see which answer was the correct one and how  many points I was able to score by fooling other players, in order to get feedback on how I  performed during this game.

### ISSUE THREAD

**Issue by Elyisha** [sopra-fs24-group-38/sopra-fs24-group-38-server#84]
**Development Tasks**
- [x] sopra-fs24-group-38/sopra-fs24-group-38-client#46
- [x] sopra-fs24-group-38/sopra-fs24-group-38-client#45
- [x] sopra-fs24-group-38/sopra-fs24-group-38-server#87
- [x] sopra-fs24-group-38/sopra-fs24-group-38-client#44
- [x] sopra-fs24-group-38/sopra-fs24-group-38-client#43
- [x] sopra-fs24-group-38/sopra-fs24-group-38-client#42
- [x] sopra-fs24-group-38/sopra-fs24-group-38-server#91
- [x] sopra-fs24-group-38/sopra-fs24-group-38-server#92
- [x] sopra-fs24-group-38/sopra-fs24-group-38-client#41

**Acceptance criteria**
- [x] The player sees how many points he himself just scored.
- [x] If a player has been fooled to click on a false definition he sees “you have been fooled by player XY”
- [x]  Whether the game is over or not is decided based on the number of rounds played and the maximal number of rounds that can be played.
- [x]  The gamecalculates and saves the number of points for each player.
- [x] After the points have been distributed, a leaderboard view is shown, presenting the scores of every player in the lobby
