### ISSUE TITLE
As a player that is in a lobby which just finished a game, I want to be able to see the game  results in order to have a competitive aspect.

### ISSUE THREAD

**Issue by Elyisha** [sopra-fs24-group-38/sopra-fs24-group-38-server#97]
**Development Tasks**
- [x] sopra-fs24-group-38/sopra-fs24-group-38-client#48
- [x] sopra-fs24-group-38/sopra-fs24-group-38-client#47
- [x] sopra-fs24-group-38/sopra-fs24-group-38-server#100
- [x] sopra-fs24-group-38/sopra-fs24-group-38-server#101

**Acceptance criteria**
- [x] The winner is visible and enlarged in the end view.
- [x] Every player’s scores, including the winner’s, is displayed in the bottom half of the screen.
